package html

import (
	"bytes"
	"fmt"
	"html/template"
	"sort"
	"strconv"

	"github.com/bctx/bctx/reporting/models"
)

// esploraSizeCaveat is duplicated here (small, fixed string) so the html
// package has no dependency on the parent reporting package.
const esploraSizeCaveat = "Transaction size/weight fields may be absent when the Esplora source did not supply them; absent sizes are reported as not available and never estimated."

// Render produces a single self-contained HTML document for the view. The CSS
// is inlined in a <style> tag; there are no <script src=>, no <link rel=
// stylesheet href=remote>, no CDN, no remote fonts and no remote images. All
// dynamic values are escaped by html/template. Output is deterministic for a
// given view.
func Render(v models.ReportView) ([]byte, error) {
	t, err := template.New("report").Funcs(funcs).Parse(pageTemplate)
	if err != nil {
		return nil, fmt.Errorf("html render: parse: %w", err)
	}
	data := struct {
		CSS  template.CSS
		View models.ReportView
	}{
		CSS:  template.CSS(styleCSS),
		View: v,
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("html render: execute: %w", err)
	}
	return buf.Bytes(), nil
}

var funcs = template.FuncMap{
	"na": func(s string) string {
		if s == "" {
			return models.NotAvailable
		}
		return s
	},
	"yesno": func(b bool) string {
		if b {
			return "yes"
		}
		return "no"
	},
	"i":   func(i int) string { return strconv.Itoa(i) },
	"i64": func(i int64) string { return strconv.FormatInt(i, 10) },
	"f2":  func(f float64) string { return strconv.FormatFloat(f, 'f', 4, 64) },
	"btc": func(f float64) string { return strconv.FormatFloat(f, 'f', 8, 64) },
	"mvkeys": func(m map[string]string) []string {
		out := make([]string, 0, len(m))
		for k := range m {
			out = append(out, k)
		}
		sort.Strings(out)
		return out
	},
	"mvget": func(m map[string]string, k string) string { return m[k] },
}

const pageTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>BCTX Forensic Report {{.View.Meta.ReportID}}</title>
<style>{{.CSS}}</style>
</head>
<body>
<h1>BCTX Forensic Report</h1>
<div class="meta"><dl>
<dt>Report ID</dt><dd class="mono">{{.View.Meta.ReportID}}</dd>
<dt>Case ID</dt><dd>{{na .View.Meta.CaseID}}</dd>
<dt>Investigation ID</dt><dd>{{na .View.Meta.InvestigationID}}</dd>
<dt>Subject</dt><dd class="mono">{{na .View.Meta.Subject}}</dd>
<dt>Subject Type</dt><dd>{{na .View.Meta.SubjectType}}</dd>
<dt>Generated At</dt><dd>{{na .View.Meta.GeneratedAt}}</dd>
<dt>Generated By</dt><dd>{{na .View.Meta.GeneratedBy}}</dd>
<dt>Schema Version</dt><dd>{{.View.Meta.SchemaVersion}}</dd>
<dt>Report Version</dt><dd>{{.View.Meta.ReportVersion}}</dd>
</dl></div>

<h2>1. Case Information</h2>
<div class="kv"><dl>
<dt>Case ID</dt><dd>{{.View.CaseInformation.CaseID}}</dd>
<dt>Created At</dt><dd>{{.View.CaseInformation.CreatedAt}}</dd>
<dt>Acquisition Provider</dt><dd>{{.View.CaseInformation.Provider}}</dd>
</dl></div>

<h2>2. Investigation Subject</h2>
<div class="kv"><dl>
<dt>Subject</dt><dd class="mono">{{.View.InvestigationSubject.Subject}}</dd>
<dt>Subject Type</dt><dd>{{.View.InvestigationSubject.SubjectType}}</dd>
<dt>Offline</dt><dd>{{yesno .View.InvestigationSubject.Offline}}</dd>
</dl></div>

<h2>3. Acquisition Summary</h2>
{{if .View.AcquisitionSummary.Available}}
<div class="kv"><dl>
<dt>Provider</dt><dd>{{na .View.AcquisitionSummary.Provider}}</dd>
<dt>Provider Version</dt><dd>{{na .View.AcquisitionSummary.ProviderVersion}}</dd>
<dt>Status</dt><dd>{{na .View.AcquisitionSummary.Status}}</dd>
<dt>Discovered</dt><dd>{{i .View.AcquisitionSummary.Discovered}}</dd>
<dt>Acquired</dt><dd>{{i .View.AcquisitionSummary.Acquired}}</dd>
<dt>Persisted</dt><dd>{{i .View.AcquisitionSummary.Persisted}}</dd>
</dl></div>
{{else}}<p class="na">not available (no acquisition sync recorded for this subject)</p>{{end}}

<h2>4. Dataset / Source Provenance</h2>
{{if .View.DatasetProvenance.Datasets}}
<table><thead><tr><th>ID</th><th>Source File</th><th>SHA-256</th><th>Schema</th><th>Tool</th><th>Imported At</th></tr></thead><tbody>
{{range .View.DatasetProvenance.Datasets}}<tr><td>{{.ID}}</td><td>{{.SourceFile}}</td><td class="mono">{{.SHA256}}</td><td>{{.SchemaVersion}}</td><td>{{.ToolVersion}}</td><td>{{.ImportedAt}}</td></tr>
{{end}}</tbody></table>
{{else}}<p class="na">not available</p>{{end}}

<h2>5. Transaction Summary</h2>
<div class="kv"><dl>
<dt>Transaction Count</dt><dd>{{i .View.TransactionSummary.Count}}</dd>
<dt>Total In (sats)</dt><dd>{{i64 .View.TransactionSummary.TotalInSats}}</dd>
<dt>Total Out (sats)</dt><dd>{{i64 .View.TransactionSummary.TotalOutSat}}</dd>
<dt>Total In (BTC)</dt><dd>{{btc .View.TransactionSummary.TotalInBTC}}</dd>
<dt>Total Out (BTC)</dt><dd>{{btc .View.TransactionSummary.TotalOutBTC}}</dd>
</dl></div>
{{if .View.TransactionSummary.TxIDs}}<ul>{{range .View.TransactionSummary.TxIDs}}<li class="mono">{{.}}</li>{{end}}</ul>{{end}}
<p class="caveat">` + esploraSizeCaveat + `</p>

<h2>6. Flow Analysis</h2>
<div class="kv"><dl>
<dt>Total Fan-In</dt><dd>{{i .View.FlowAnalysis.TotalFanIn}}</dd>
<dt>Total Fan-Out</dt><dd>{{i .View.FlowAnalysis.TotalFanOut}}</dd>
</dl></div>

<h2>7. Graph Summary</h2>
{{if .View.GraphSummary.Available}}
<div class="kv"><dl>
<dt>Center</dt><dd class="mono">{{na .View.GraphSummary.Center}}</dd>
<dt>Depth</dt><dd>{{i .View.GraphSummary.Depth}}</dd>
<dt>Node Count</dt><dd>{{i .View.GraphSummary.NodeCount}}</dd>
<dt>Edge Count</dt><dd>{{i .View.GraphSummary.EdgeCount}}</dd>
</dl></div>
{{else}}<p class="na">not available (no subgraph extracted)</p>{{end}}

<h2>8. Related Wallets</h2>
<div class="kv"><dl>
<dt>Count</dt><dd>{{i .View.RelatedWallets.Count}}</dd>
<dt>Relationship</dt><dd>{{.View.RelatedWallets.Relationship}}</dd>
</dl></div>
{{if .View.RelatedWallets.Members}}<ul>{{range .View.RelatedWallets.Members}}<li class="mono">{{.}}</li>{{end}}</ul>{{end}}

<h2>9. Entity Signals</h2>
<div class="kv"><dl><dt>Inferred Cluster Count</dt><dd>{{i .View.EntitySignals.ClusterCount}}</dd></dl></div>

<h2>10. Network Observations</h2>
<div class="kv"><dl><dt>Correlated Observation Count</dt><dd>{{i .View.NetworkObservations.Count}}</dd></dl></div>

<h2>11. ML Signals</h2>
{{if .View.MLSignals.Predictions}}
<table><thead><tr><th>Model</th><th>Version</th><th>Feature Schema</th><th>Score</th><th>Confidence</th></tr></thead><tbody>
{{range .View.MLSignals.Predictions}}<tr><td>{{.Model}}</td><td>{{.ModelVersion}}</td><td>{{na .FeatureSchema}}</td><td>{{f2 .Score}}</td><td>{{f2 .Confidence}}</td></tr>
{{end}}</tbody></table>
{{else}}<p class="na">not available</p>{{end}}

<h2>12. Risk Assessment</h2>
<div class="kv"><dl>
<dt>Score</dt><dd>{{i .View.RiskAssessment.Score}} / 100</dd>
<dt>Confidence</dt><dd>{{f2 .View.RiskAssessment.Confidence}}</dd>
</dl></div>
{{if .View.RiskAssessment.Signals}}
<table><thead><tr><th>Signal</th><th>Score</th><th>Weight</th><th>Description</th></tr></thead><tbody>
{{range .View.RiskAssessment.Signals}}<tr><td>{{.Name}}</td><td>{{f2 .Score}}</td><td>{{f2 .Weight}}</td><td>{{.Description}}</td></tr>
{{end}}</tbody></table>{{end}}

<h2>13. Risk Deltas</h2>
{{if .View.RiskDeltas.Deltas}}
<table><thead><tr><th>Subject</th><th>Previous</th><th>Current</th><th>Delta</th><th>Timestamp</th></tr></thead><tbody>
{{range .View.RiskDeltas.Deltas}}<tr><td class="mono">{{.Subject}}</td><td>{{i .PreviousScore}}</td><td>{{i .CurrentScore}}</td><td>{{i .Delta}}</td><td>{{na .Timestamp}}</td></tr>
{{end}}</tbody></table>
{{else}}<p class="na">not available</p>{{end}}

<h2>14. Alert History</h2>
{{if .View.AlertHistory.Alerts}}
<table><thead><tr><th>ID</th><th>Type</th><th>Risk</th><th>Confidence</th><th>Status</th><th>Reason</th><th>Created At</th></tr></thead><tbody>
{{range .View.AlertHistory.Alerts}}<tr><td>{{.ID}}</td><td>{{.Type}}</td><td>{{i .Risk}}</td><td>{{f2 .Confidence}}</td><td>{{.Status}}</td><td>{{.Reason}}</td><td>{{.CreatedAt}}</td></tr>
{{end}}</tbody></table>
{{else}}<p class="na">not available</p>{{end}}

<h2>15. Evidence</h2>
{{if .View.Evidence.Items}}
<ul>{{range .View.Evidence.Items}}<li><strong>{{.ID}}</strong> ({{.Type}}, {{.Severity}}, confidence {{f2 .Confidence}}): {{.Description}}{{if .SourceRecords}}<br>source records: {{range $i, $r := .SourceRecords}}{{if $i}}, {{end}}<span class="mono">{{$r}}</span>{{end}}{{end}}</li>{{end}}</ul>
{{else}}<p class="na">not available</p>{{end}}

<h2>16. Timeline</h2>
{{if .View.Timeline.Events}}
<table><thead><tr><th>Timestamp</th><th>Kind</th><th>ID</th><th>Detail</th></tr></thead><tbody>
{{range .View.Timeline.Events}}<tr><td>{{na .Timestamp}}</td><td>{{.Kind}}</td><td class="mono">{{.ID}}</td><td>{{.Detail}}</td></tr>
{{end}}</tbody></table>
{{else}}<p class="na">not available</p>{{end}}

<h2>17. Graph Paths</h2>
{{if .View.GraphPaths.Paths}}
<ul>{{range .View.GraphPaths.Paths}}<li>{{.Seed}} &rarr; {{.Target}} (distance {{i .Distance}}, contribution {{f2 .Contribution}}): {{range $i, $n := .Path}}{{if $i}} &rarr; {{end}}<span class="mono">{{$n}}</span>{{end}}</li>{{end}}</ul>
{{else}}<p class="na">not available</p>{{end}}

<h2>18. Limitations</h2>
<ul>{{range .View.Limitations.Notes}}<li>{{.}}</li>{{end}}</ul>

<h2>19. Data Quality</h2>
<div class="kv"><dl>
<dt>Transaction Count</dt><dd>{{i .View.DataQuality.TransactionCount}}</dd>
<dt>Network Observation Count</dt><dd>{{i .View.DataQuality.NetworkObservationCount}}</dd>
<dt>Has Graph</dt><dd>{{yesno .View.DataQuality.HasGraph}}</dd>
</dl></div>

<h2>20. Offline / Connected State</h2>
<div class="kv"><dl>
<dt>Offline</dt><dd>{{yesno .View.OfflineConnected.Offline}}</dd>
<dt>Monitor State</dt><dd>{{.View.OfflineConnected.MonitorState}}</dd>
<dt>Detail</dt><dd>{{na .View.OfflineConnected.Detail}}</dd>
</dl></div>

<h2>21. Generation Metadata</h2>
<div class="kv"><dl>
<dt>Generated At</dt><dd>{{na .View.GenerationMetadata.GeneratedAt}}</dd>
<dt>Generated By</dt><dd>{{na .View.GenerationMetadata.GeneratedBy}}</dd>
<dt>Schema Version</dt><dd>{{.View.GenerationMetadata.SchemaVersion}}</dd>
<dt>Generator Version</dt><dd>{{.View.GenerationMetadata.GeneratorVersion}}</dd>
<dt>Snapshot SHA-256</dt><dd class="mono">{{.View.GenerationMetadata.SnapshotSHA256}}</dd>
<dt>Feature Schema</dt><dd>{{na .View.GenerationMetadata.FeatureSchema}}</dd>
</dl></div>
{{$mv := .View.GenerationMetadata.ModelVersions}}{{if $mv}}<ul>{{range mvkeys $mv}}<li><span class="mono">{{.}}</span>: {{mvget $mv .}}</li>{{end}}</ul>{{end}}

<footer>Generated by BCTX reporting. Self-contained offline report; no network access required to view.</footer>
</body>
</html>
`
