package pdf

import (
	"fmt"
	"math"
	"strconv"

	"github.com/bctx/bctx/reporting/models"
)

// esploraSizeCaveat is duplicated here (small, fixed string) so the pdf package
// has no dependency on the parent reporting package.
const esploraSizeCaveat = "Transaction size/weight fields may be absent when the Esplora source did not supply them; absent sizes are reported as not available and never estimated."

// Render builds a deterministic PDF-1.4 document from the view in the §7.3
// content order and returns its bytes. idHex is the snapshot hash, used as the
// content-derived /ID. No wall-clock is read here: the visible generated_at is
// drawn text fed from the view (service clock), never embedded as a PDF date.
func Render(v models.ReportView, idHex string) ([]byte, error) {
	doc := newDocument()
	l := newLayout(doc)

	// Title.
	l.title("BCTX Forensic Report")
	l.keyValue("Report ID", v.Meta.ReportID)
	l.keyValue("Generated At", na(v.Meta.GeneratedAt))
	l.keyValue("Generated By", na(v.Meta.GeneratedBy))
	l.keyValue("Schema Version", v.Meta.SchemaVersion)
	l.keyValue("Report Version", v.Meta.ReportVersion)

	// Case.
	l.heading("Case")
	l.keyValue("Case ID", v.CaseInformation.CaseID)
	l.keyValue("Created At", v.CaseInformation.CreatedAt)
	l.keyValue("Acquisition Provider", v.CaseInformation.Provider)

	// Subject.
	l.heading("Subject")
	l.keyValue("Subject", v.InvestigationSubject.Subject)
	l.keyValue("Subject Type", v.InvestigationSubject.SubjectType)
	l.keyValue("Offline", yesno(v.InvestigationSubject.Offline))

	// Risk + confidence.
	l.heading("Risk Assessment")
	l.keyValue("Score", strconv.Itoa(v.RiskAssessment.Score)+" / 100")
	l.keyValue("Confidence", f2(v.RiskAssessment.Confidence))
	if len(v.RiskAssessment.Signals) > 0 {
		rows := make([][]string, 0, len(v.RiskAssessment.Signals))
		for _, s := range v.RiskAssessment.Signals {
			rows = append(rows, []string{s.Name, f2(s.Score), f2(s.Weight), s.Description})
		}
		l.table([]string{"Signal", "Score", "Weight", "Description"}, rows, []float64{2, 1, 1, 4})
	}

	// Key findings (evidence-truthful language).
	l.heading("Key Findings")
	l.keyValue("Inferred Related Wallets", strconv.Itoa(v.RelatedWallets.Count))
	l.keyValue("Relationship", v.RelatedWallets.Relationship)
	l.keyValue("Inferred Entity Clusters", strconv.Itoa(v.EntitySignals.ClusterCount))
	l.keyValue("Correlated Network Observations", strconv.Itoa(v.NetworkObservations.Count))
	if len(v.MLSignals.Predictions) > 0 {
		rows := make([][]string, 0, len(v.MLSignals.Predictions))
		for _, p := range v.MLSignals.Predictions {
			rows = append(rows, []string{p.Model, p.ModelVersion, f2(p.Score), f2(p.Confidence)})
		}
		l.table([]string{"Model", "Version", "Score", "Confidence"}, rows, []float64{3, 2, 1, 1})
	}

	// Timeline.
	l.heading("Timeline")
	if len(v.Timeline.Events) == 0 {
		l.paragraph(Helvetica, bodySize, models.NotAvailable)
	} else {
		rows := make([][]string, 0, len(v.Timeline.Events))
		for _, e := range v.Timeline.Events {
			rows = append(rows, []string{na(e.Timestamp), string(e.Kind), e.ID, e.Detail})
		}
		l.table([]string{"Timestamp", "Kind", "ID", "Detail"}, rows, []float64{3, 2, 3, 4})
	}

	// Transaction summary.
	l.heading("Transaction Summary")
	l.keyValue("Transaction Count", strconv.Itoa(v.TransactionSummary.Count))
	l.keyValue("Total In (sats)", strconv.FormatInt(v.TransactionSummary.TotalInSats, 10))
	l.keyValue("Total Out (sats)", strconv.FormatInt(v.TransactionSummary.TotalOutSat, 10))
	l.keyValue("Total In (BTC)", btc(v.TransactionSummary.TotalInBTC))
	l.keyValue("Total Out (BTC)", btc(v.TransactionSummary.TotalOutBTC))
	l.paragraph(Helvetica, bodySize, esploraSizeCaveat)

	// Graph summary (+ optional vector drawing of the subgraph).
	l.heading("Graph Summary")
	if v.GraphSummary.Available {
		l.keyValue("Center", v.GraphSummary.Center)
		l.keyValue("Depth", strconv.Itoa(v.GraphSummary.Depth))
		l.keyValue("Node Count", strconv.Itoa(v.GraphSummary.NodeCount))
		l.keyValue("Edge Count", strconv.Itoa(v.GraphSummary.EdgeCount))
		l.drawGraph(v)
	} else {
		l.paragraph(Helvetica, bodySize, models.NotAvailable+" (no subgraph extracted)")
	}

	// Evidence.
	l.heading("Evidence")
	if len(v.Evidence.Items) == 0 {
		l.paragraph(Helvetica, bodySize, models.NotAvailable)
	} else {
		for _, e := range v.Evidence.Items {
			l.bullet(fmt.Sprintf("%s (%s, %s, confidence %s): %s",
				e.ID, e.Type, e.Severity, f2(e.Confidence), e.Description))
		}
	}

	// Alerts.
	l.heading("Alerts")
	if len(v.AlertHistory.Alerts) == 0 {
		l.paragraph(Helvetica, bodySize, models.NotAvailable)
	} else {
		rows := make([][]string, 0, len(v.AlertHistory.Alerts))
		for _, a := range v.AlertHistory.Alerts {
			rows = append(rows, []string{a.ID, a.Type, strconv.Itoa(a.Risk), f2(a.Confidence), a.Status})
		}
		l.table([]string{"ID", "Type", "Risk", "Confidence", "Status"}, rows, []float64{3, 2, 1, 1, 2})
	}

	// Provenance.
	l.heading("Provenance")
	l.keyValue("Snapshot SHA-256", v.GenerationMetadata.SnapshotSHA256)
	l.keyValue("Feature Schema", na(v.GenerationMetadata.FeatureSchema))
	if len(v.DatasetProvenance.Datasets) == 0 {
		l.paragraph(Helvetica, bodySize, "Datasets: "+models.NotAvailable)
	} else {
		rows := make([][]string, 0, len(v.DatasetProvenance.Datasets))
		for _, d := range v.DatasetProvenance.Datasets {
			rows = append(rows, []string{d.ID, d.SourceFile, d.SHA256, d.ImportedAt})
		}
		l.table([]string{"ID", "Source File", "SHA-256", "Imported At"}, rows, []float64{2, 3, 4, 2})
	}

	// Limitations.
	l.heading("Limitations")
	for _, n := range v.Limitations.Notes {
		l.bullet(n)
	}

	return doc.write(idHex)
}

// drawGraph renders the result's subgraph as a simple vector diagram using
// re/m/l/S operators. Nodes are placed on a circle and edges drawn as lines.
// It is deterministic (node order is the view's node order) and uses no raster
// or external image. Only a bounded number of nodes are drawn to keep the
// diagram legible.
func (l *layout) drawGraph(v models.ReportView) {
	const (
		maxNodes = 12
		radius   = 90.0
		boxW     = 70.0
		boxH     = 16.0
	)
	n := v.GraphSummary.NodeCount
	if n <= 0 {
		return
	}
	if n > maxNodes {
		n = maxNodes
	}
	diagramH := 2*radius + boxH + 20
	l.ensure(diagramH)
	cx := marginLeft + contentWidth/2
	cyTop := l.curY + radius + boxH/2 + 10
	cy := pdfY(cyTop)

	type pt struct{ x, y float64 }
	pts := make([]pt, n)
	for i := 0; i < n; i++ {
		ang := 2 * math.Pi * float64(i) / float64(n)
		pts[i] = pt{
			x: cx + radius*math.Cos(ang),
			y: cy + radius*math.Sin(ang),
		}
	}
	// Edges: connect each node to the next (ring) for a deterministic figure.
	fmt.Fprintf(&l.cur.content, "0.6 w\n")
	for i := 0; i < n; i++ {
		j := (i + 1) % n
		fmt.Fprintf(&l.cur.content, "%s %s m %s %s l S\n",
			ftoa(pts[i].x), ftoa(pts[i].y), ftoa(pts[j].x), ftoa(pts[j].y))
	}
	// Node boxes + labels.
	for i := 0; i < n; i++ {
		x0 := pts[i].x - boxW/2
		y0 := pts[i].y - boxH/2
		fmt.Fprintf(&l.cur.content, "%s %s %s %s re S\n",
			ftoa(x0), ftoa(y0), ftoa(boxW), ftoa(boxH))
		label := "node " + strconv.Itoa(i+1)
		fmt.Fprintf(&l.cur.content, "BT /%s %s %s %s Td (%s) Tj ET\n",
			l.doc.resourceName(Courier), ftoa(7),
			ftoa(x0+3), ftoa(y0+4), escapeText(label))
	}
	l.curY += diagramH
}

func na(s string) string {
	if s == "" {
		return models.NotAvailable
	}
	return s
}

func yesno(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func f2(f float64) string  { return strconv.FormatFloat(f, 'f', 4, 64) }
func btc(f float64) string { return strconv.FormatFloat(f, 'f', 8, 64) }
